In [11]:
import os
import sys
current_filename = os.path.abspath("./kaggle.ipynb")
parent_dir = os.path.dirname(current_filename)
great_parent_dir = os.path.dirname(parent_dir)
sys.path.append(great_parent_dir)

In [18]:
import pandas as pd

In [15]:
from tools.config_file import NewUserPredictParams
params = NewUserPredictParams()

In [21]:
train_csv = pd.read_csv(params.train_csv)
test_cvs = pd.read_csv(params.test_csv)
train_csv

,uuid,eid,x1,x2,x3,x4,x5,x6,x7,x8,...,key5,key6,key7,key8,key9,one_hot,date,hour,weekday,target
0,0,26,4,0,41,107,206,1,0,1,...,-1,-1,-1,-1,-1,192,18,9,1,0
1,1,26,4,0,41,24,283,4,8,1,...,-1,-1,-1,-1,-1,192,11,13,1,0
2,2,8,4,0,41,71,288,4,7,1,...,-1,-1,-1,-1,-1,0,15,7,5,0
3,3,11,1,3,41,17,366,1,6,1,...,-1,-1,-1,-1,-1,0,16,0,6,0
4,4,26,0,3,41,92,383,4,8,1,...,-1,-1,-1,-1,-1,192,16,7,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620351,620351,2,4,0,41,104,37,4,4,1,...,14,-1,-1,-1,-1,48,10,12,0,0
620352,620352,8,4,0,41,104,37,1,6,1,...,-1,-1,-1,-1,-1,0,16,6,6,0
620353,620353,41,0,2,41,104,37,4,2,0,...,-1,-1,-1,-1,-1,384,9,8,6,1
620354,620354,26,4,0,41,17,366,1,6,1,...,-1,-1,-1,-1,-1,192,18,4,1,0
620355,620355,41,2,2,41,71,288,4,2,0,...,-1,-1,-1,-1,-1,384,13,8,3,0

In [ ]:
for dirname, _, filenames in os.walk('../dataset/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))